# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SeedServe
version:      0.2.0
version_from: lib/Net/SeedServe.pm
installdirs:  site
requires:
    IO::All:                       0.33
    Test::More:                    0
    Time::HiRes:                   1.59

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
